smileidentity/flutter

CHANGELOG.md, android/build.gradle, pubspec.yaml
Story: N/A
Release `10.0.0-beta05` with more android fixes
=> Release 10.0.0-beta05

ios/Classes/SmileIDDocumentVerification.swift, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift
Fixed wrong iOS Struct Decoding
=> Fixed wrong iOS Struct Decoding

ios/Classes/SmileIDDocumentVerification.swift, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift
=> Fix Wrong JSON on iOS

CHANGELOG.md, android/build.gradle, android/src/main/kotlin/com/smileidentity/flutter/SmileIDDocumentVerification.kt, android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieAuthentication.kt, android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieEnrollment.kt, example/ios/Podfile.lock, ios/Classes/SmileIDDocumentVerification.swift, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift, ios/smile_id.podspec, lib/smile_id_document_verification.dart, lib/smile_id_smart_selfie_authentication.dart, lib/smile_id_smart_selfie_enrollment.dart
Rename partnerParams to extraPartnerParams
=> Rename partnerParams to extraPartnerParams

example/pubspec.lock, pubspec.yaml
=> Prepare 10.0.0-beta07 release

CHANGELOG.md, pubspec.yaml
Bump versions for 10.0.0-beta08
=> Prepare 10.0.0-beta08

CHANGELOG.md, android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/smile_id.podspec, pubspec.yaml
Depends on https://github.com/smileidentity/ios/pull/106 and https://github.com/smileidentity/android/pull/275
=> Prepare for 10.0.0 release

CHANGELOG.md, android/build.gradle, android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieAuthentication.kt, example/ios/Podfile.lock, ios/smile_id.podspec, lib/smile_id_smart_selfie_authentication.dart, pubspec.yaml
=> Fixed Instructions on SmartSelfieAuthentication

.github/workflows/release_android.yml, .github/workflows/release_ios.yml
=> update android and ios versions on new release

CHANGELOG.md, example/ios/Podfile.lock, ios/smile_id.podspec, pubspec.yaml
=> Update to iOS v10.0.10

CHANGELOG.md, android/src/main/kotlin/com/smileidentity/flutter/SmileIDPlugin.kt, android/src/main/kotlin/com/smileidentity/flutter/generated/SmileIDMessages.g.kt, example/ios/Podfile.lock, ios/Classes/SmileIDMessages.g.swift, ios/Classes/SmileIDPlugin.swift, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift, ios/smile_id.podspec, lib/smile_id.dart, lib/smileid_messages.g.dart, pigeon/messages.dart
Story: https://app.shortcut.com/smileid/story/12502/add-offline-mode-functionality-to-v10-wrappers-flutter
Extending the offline mode on native android and iOS to the Flutter SDK
=> Extend Offline Mode functionality on Flutter

CHANGELOG.md, example/ios/Podfile.lock, ios/Classes/SmileIDPlugin.swift, ios/smile_id.podspec, pubspec.yaml
Story: https://app.shortcut.com/smileid/story/12926
Updates networking methods to use asynchronous Swift code
This can go in once https://github.com/smileidentity/ios/pull/183 is released
Run jobs from the Flutter sample app
=> Make iOS networking methods async

.github/workflows/build.yaml, CHANGELOG.md, android/build.gradle, example/android/app/build.gradle, example/android/build.gradle, pubspec.yaml
Story: https://app.shortcut.com/smileid/story/13102
Fixes build issues on Android by explicitly setting jvmTarget to 17
=> Set jvmTarget to 17

CHANGELOG.md, example/ios/Podfile.lock, ios/smile_id.podspec, pubspec.yaml
=> Update iOS and Prepare Flutter Release

CHANGELOG.md, android/build.gradle, android/src/main/kotlin/com/smileidentity/flutter/Mapper.kt, android/src/main/kotlin/com/smileidentity/flutter/generated/SmileIDMessages.g.kt, example/ios/Podfile.lock, example/lib/main.dart, example/pubspec.lock, ios/Classes/Mapper.swift, ios/Classes/SmileIDBiometricKYC.swift, ios/Classes/SmileIDDocumentVerification.swift, ios/Classes/SmileIDEnhancedDocumentVerification.swift, ios/Classes/SmileIDMessages.g.swift, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift, ios/smile_id.podspec, lib/smileid_messages.g.dart, pigeon/messages.dart, pubspec.yaml
=> Fix JSON bug on Flutter

example/ios/Podfile.lock, example/pubspec.lock, ios/Classes/SmileIDPlugin.swift
Update job status polling on flutter
=> feature: job status polling updates

CHANGELOG.md, example/ios/Podfile.lock, example/pubspec.lock, ios/smile_id.podspec, pubspec.yaml
=> Release v10.1.9

example/ios/Podfile.lock, ios/Classes/SmileIDPlugin.swift, ios/smile_id.podspec
=> iOS v10.2.11

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
=> Bump up AGP Versions

CHANGELOG.md, android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieAuthentication.kt, android/src/main/kotlin/com/smileidentity/flutter/SmileIDSmartSelfieEnrollment.kt, example/ios/Podfile.lock, ios/Classes/SmileIDSmartSelfieAuthentication.swift, ios/Classes/SmileIDSmartSelfieEnrollment.swift, ios/smile_id.podspec, lib/smile_id_smart_selfie_authentication.dart, lib/smile_id_smart_selfie_enrollment.dart, pubspec.yaml
Story: https://app.shortcut.com/smileid/story/13873/fix-bug-issue-with-flutter-sdk-from-10-1-8-onwards-ignoring-provided-jobid
=> Remove jobId in Biometric Jobs

.github/workflows/auto-author-assign.yml
=> auto assign pr workflow

CHANGELOG.md, android/build.gradle, example/android/app/build.gradle, pubspec.yaml
To support versions below Kotlin 2.0
=> Skip Metadata Version Check

CHANGELOG.md, example/lib/main.dart, ios/Classes/Mapper.swift, pubspec.yaml
Story: https://app.shortcut.com/smileid/story/14817/fix-extra-partner-params-sent-in-enhanced-kyc-requests-from-flutter-sdk-are-not-recognized-on-ios
=> Add Missing Extras on iOS Mapper
